export const KECAMATAN = [
  { name: 'CIWIDEY', id: 1 },
  { name: 'RANCABALI', id: 2 },
  { name: 'PASIRJAMBU', id: 3 },
  { name: 'CIMAUNG', id: 4 },
  { name: 'PANGALENGAN', id: 5 },
  { name: 'KERTASARI', id: 6 },
  { name: 'PACET', id: 7 },
  { name: 'IBUN', id: 8 },
  { name: 'PASEH', id: 9 },
  { name: 'CIKANCUNG', id: 10 },
  { name: 'CICALENGKA', id: 11 },
  { name: 'NAGREG', id: 12 },
  { name: 'RANCAEKEK', id: 13 },
  { name: 'MAJALAYA', id: 14 },
  { name: 'SOLOKAN JERUK', id: 15 },
  { name: 'CIPARAY', id: 16 },
  { name: 'BALEENDAH', id: 17 },
  { name: 'ARJASARI', id: 18 },
  { name: 'BANJARAN', id: 19 },
  { name: 'CANGKUANG', id: 20 },
  { name: 'PAMEUNGPEUK', id: 21 },
  { name: 'KATAPANG', id: 22 },
  { name: 'SOREANG', id: 23 },
  { name: 'KUTAWARINGIN', id: 24 },
  { name: 'MARGAASIH', id: 25 },
  { name: 'MARGAHAYU', id: 26 },
  { name: 'DAYEUHKOLOT', id: 27 },
  { name: 'BOJONGSOANG', id: 28 },
  { name: 'CILEUNYI', id: 29 },
  { name: 'CILENGKRANG', id: 30 },
  { name: 'CIMENYAN', id: 31 },
];
